version: "3.1"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
